# Generated by Django 2.1.7 on 2019-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite_town',
            field=models.CharField(blank=True, choices=[('CASTLE', 'Castle'), ('RAMPART', 'Rampart'), ('FORTRESS', 'Fortress'), ('INFERNO', 'Inferno'), ('NECROPOLIS', 'Necropolis'), ('DUNGEON', 'Dungeon'), ('STRONGHOLD', 'Stronghold'), ('TOWER', 'Tower')], max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='footer_phrase',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
