# Generated by Django 2.1.7 on 2019-02-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='forum/category/images/default.jpg', upload_to='forum/category/images/')),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
    ]
