# Generated by Django 2.1.7 on 2019-02-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Footer',
        ),
    ]
