# Generated by Django 2.1.7 on 2019-02-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190227_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='forum/category/default/default.jpg', upload_to='forum/category/'),
        ),
    ]
