# Generated by Django 2.1.7 on 2019-04-08 12:36

from django.db import migrations


def create_apps(apps, schema_editor):
    Application = apps.get_model('landing_page', 'Application')
    Application.objects.bulk_create([
        Application(name="Forum", image="landing_page/application/Advanced_Tactics.png",
                    summary="Forum zrzeszające społeczność Heroes III, dołącz dziś!",
                    urlCategory="categories"),

        Application(name="Gra", image="landing_page/application/Expert_Necromancy.png",
                    summary="Zagraj w symulację bitwy z Heroes III !", urlCategory="servers"),

        Application(name="Czat", image="///", summary="Pogadaj z nami na interaktywnym czacie.",
                    urlCategory="placeholder"),

        Application(name="Ranking", image="///",
                    summary="Poznaj statystyki graczy i zmierz się z najlepszymi!", urlCategory="charts")
    ])


def delete_apps(apps, schema_editor):
    Application = apps.get_model('landing_page', 'Application')
    Application.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_apps, reverse_code=delete_apps, atomic=True),
    ]
