# Generated by Django 2.1.7 on 2019-04-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='urlCategory',
            field=models.CharField(default='', max_length=20),
        ),
    ]
